version: "3.9"

services:
  food_service:
    image: 'food-service'
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/food-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
  postgres:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgres/data
    environment:
      POSTGRES_DB: "food-db"
      POSTGRES_PASSWORD: "password"
    ports:
      - "9090:5432"
    healthcheck:
      test: ["CMD-SHELL", pg_isready -U postgres]
      interval: 5s
      timeout: 10s
      retries: 3
volumes:
  pgdata: